---
title: "ARTS Planet Basemap Grids to Download"
author: "Heidi Rodenhizer"
date: "`r Sys.Date()`"
output: html_document
---

# Load Packages

```{r}
library(sf)
library(rnaturalearth)
library(viridis)
library(tidyverse)
theme_set(theme_bw())
```

# Load Data

```{r}
arts = st_read(
  '../ARTS/ARTS_main_dataset/v.6.0.0/ARTS_main_dataset_v.6.0.0.geojson'
)
planet_grids = st_read('./data/circumpolar_global_basemap_grids_2024.geojson')
world = rnaturalearth::ne_countries(scale = "large", returnclass = "sf")
world = world |>
  st_transform(3413) |>
  st_crop(
    planet_grids |>
      st_transform(3413) |>
      st_bbox() |>
      st_as_sfc() |>
      st_buffer(dist = 200000) |>
      st_bbox()
  )
```

# ARTS Tiles

```{r}
arts_tiles = arts |>
  st_centroid() |>
  st_buffer(
    dist = sqrt(256^2 + 256^2) * 4.78, # length of center point to corner for training tile with 512 pixel sides
    endCapStyle = "ROUND" # use a circular buffer because we don't know the CRS that we will use with the final ARTS training tiles - this ensures the proper distance regardless of the orientation of the final tiles'
  )
```

# Intersection

```{r}
arts_grids = planet_grids %>%
  st_transform(st_crs(arts)) %>%
  st_filter(arts) %>%
  mutate(
    name = as.character(name),
    year = name |>
      str_match("[:digit:]{4}") |>
      as.integer(),
    grid_column = id |>
      str_split_i("-", 1) |>
      as.integer(),
    grid_row = id |>
      str_split_i("-", 2) |>
      as.integer(),
    basemap_name = paste0(
      "global_quarterly_",
      year,
      "q3_mosaic"
    ),
    delivery_location = paste0(
      "planet_basemaps/global_quarterly/",
      year,
      "/q3/",
      grid_column,
      "/",
      grid_row,
      "/"
    )
  ) |>
  select(
    year, 
    id, 
    grid_column, 
    grid_row, 
    basemap_name, 
    delivery_location, 
    link
    ) |>
  arrange(year, grid_column, grid_row)

print(
  paste(
    'Storage Space for Planet Basemap Grids in 2024:',
    round(
      nrow(arts_grids) * 30 / 1000 / 1000,
      2
    ),
    '(TB)'
  )
)
```

# Map of Output

```{r}
ggplot() +
  geom_sf(
    data = arts,
    color = 'black',
    fill = 'black',
    size = 0.1,
    linewidth = 0.1
  ) +
  geom_sf(
    data = arts_grids,
    color = "darkred",
    fill = 'transparent',
  )
```

# Save Output

```{r}
st_write(
  arts_grids,
  './data/planet_grids_2024_artsv.6.0.0.geojson'
  )
```

